In [40]:
import pandas as pd

In [41]:
# URL del archivo Excel de INEGI
url = "https://www.inegi.org.mx/contenidos/datosprimarios/iavl/tabulados/8_Ventas_serie.xlsx"

# Descargar y leer el Excel
autos = pd.read_excel(url)

In [42]:
# Consultar los primeros registros
autos.head(1)

,INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Venta al público de vehículos ligeros por marc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# Revisar dimensiones y columnas
print(autos.shape)
print(autos.columns)

(107387, 10)
Index(['INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')

In [44]:
## Extraer la fila cuatro y todas las columnas porque ahi se encuentran los nombres
nombres = autos.iloc[4,:]
nombres

INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026           Tema
Unnamed: 1                                                                                                                  Año
Unnamed: 2                                                                                                                  Mes
Unnamed: 3                                                                                                                Marca
Unnamed: 4                                                                                                               Modelo
Unnamed: 5                                                                                                                 Tipo
Unnamed: 6                                                                                                             Segmento
Unnamed: 7                                                                                                               Origen
Unnamed: 8                                                                                                          País origen
Unnamed: 9                                                                                                             Cantidad
Name: 4, dtype: object

In [45]:
# Seleccionar desde la fila 5 y todas las columnas 
datos = autos.iloc[5:,:]

In [46]:
datos.head(1)

,INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
5,Venta al publico de vehículos,2005,Enero,Acura,Mdx,Camiones ligeros,SUV's,Importado,Canadá,18

In [47]:
datos.columns = nombres

In [48]:
datos.head(1)

4,Tema,Año,Mes,Marca,Modelo,Tipo,Segmento,Origen,País origen,Cantidad
5,Venta al publico de vehículos,2005,Enero,Acura,Mdx,Camiones ligeros,SUV's,Importado,Canadá,18

In [49]:
# La columna Tema solo tiene basura
datos['Tema'].unique()

<ArrowStringArray>
[                                                                                                                                                  'Venta al publico de vehículos',
                                   'Notas: Los registros identificados con (-)  en la columna de Cantidad, indican que no se producía dicho modelo en el mes y año de referencia.',
 '             Las cifras negativas representan un saldo y corresponden a unidades vehiculares que fueron devueltas y se registran en un mes, las cuales pueden incluir vehículos',
                                                                                                                         '             que se devolvieron en periodos anteriores.',
                                                                                                                         '            Cifras revisadas a partir de enero de 2024.',
                                                                                                                                  'Fecha de actualización: 07 de octubre de 2026.',
                                                                                         'Fuente: INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros.']
Length: 7, dtype: str

In [50]:
## Eliminar la columna tema

datos.drop(['Tema'], axis=1, inplace=True)

In [51]:
datos.head(1)

4,Año,Mes,Marca,Modelo,Tipo,Segmento,Origen,País origen,Cantidad
5,2005,Enero,Acura,Mdx,Camiones ligeros,SUV's,Importado,Canadá,18

In [ ]:
### Además tengo más cambios