In [1]:
import pandas as pd

In [2]:
# URL del archivo Excel de INEGI
url = "https://www.inegi.org.mx/contenidos/datosprimarios/iavl/tabulados/8_Ventas_serie.xlsx"

# Descargar y leer el Excel
autos = pd.read_excel(url)

In [3]:
# Consultar los primeros registros
autos.head(1)

,INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Venta al público de vehículos ligeros por marc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Revisar dimensiones y columnas
print(autos.shape)
print(autos.columns)

(107387, 10)
Index(['INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')

In [5]:
## Extraer la fila cuatro y todas las columnas porque ahi se encuentran los nombres
nombres = autos.iloc[4,:]
nombres

INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026           Tema
Unnamed: 1                                                                                                                  Año
Unnamed: 2                                                                                                                  Mes
Unnamed: 3                                                                                                                Marca
Unnamed: 4                                                                                                               Modelo
Unnamed: 5                                                                                                                 Tipo
Unnamed: 6                                                                                                             Segmento
Unnamed: 7                                                                                                               Origen
Unnamed: 8                                                                                                          País origen
Unnamed: 9                                                                                                             Cantidad
Name: 4, dtype: object

In [6]:
# Seleccionar desde la fila 5 y todas las columnas 
datos = autos.iloc[5:,:]

In [7]:
datos.head(1)

,INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros. Fecha de publicación: 07/10/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
5,Venta al publico de vehículos,2005,Enero,Acura,Mdx,Camiones ligeros,SUV's,Importado,Canadá,18

In [8]:
datos.columns = nombres

In [9]:
datos.head(1)

4,Tema,Año,Mes,Marca,Modelo,Tipo,Segmento,Origen,País origen,Cantidad
5,Venta al publico de vehículos,2005,Enero,Acura,Mdx,Camiones ligeros,SUV's,Importado,Canadá,18

In [10]:
# La columna Tema solo tiene basura
datos['Tema'].unique()

<ArrowStringArray>
[                                                                                                                                                  'Venta al publico de vehículos',
                                   'Notas: Los registros identificados con (-)  en la columna de Cantidad, indican que no se producía dicho modelo en el mes y año de referencia.',
 '             Las cifras negativas representan un saldo y corresponden a unidades vehiculares que fueron devueltas y se registran en un mes, las cuales pueden incluir vehículos',
                                                                                                                         '             que se devolvieron en periodos anteriores.',
                                                                                                                         '            Cifras revisadas a partir de enero de 2024.',
                                                                                                                                  'Fecha de actualización: 07 de octubre de 2026.',
                                                                                         'Fuente: INEGI. Registro Administrativo de la Industria Automotriz de Vehículos Ligeros.']
Length: 7, dtype: str

In [11]:
## Eliminar la columna tema

datos.drop(['Tema'], axis=1, inplace=True)

In [12]:
datos.head(1)

4,Año,Mes,Marca,Modelo,Tipo,Segmento,Origen,País origen,Cantidad
5,2005,Enero,Acura,Mdx,Camiones ligeros,SUV's,Importado,Canadá,18

In [ ]:
### Además tengo más cambios

In [15]:
datos['Mes'].unique()

<ArrowStringArray>
[     'Enero',    'Febrero',      'Marzo',      'Abril',       'Mayo',
      'Junio',      'Julio',     'Agosto', 'Septiembre',    'Octubre',
  'Noviembre',  'Diciembre',          nan]
Length: 13, dtype: str

In [16]:
## Mapear los datos 
meses = {'Enero':1,'Febrero':2,'Marzo':3,'Abril':4,'Mayo':5,
         'Junio':6,'Julio':7,'Agosto':8,'Septiembre':9,'Octubre':10,'Noviembre':11,
         'Diciembre':12}
meses

{'Enero': 1,
 'Febrero': 2,
 'Marzo': 3,
 'Abril': 4,
 'Mayo': 5,
 'Junio': 6,
 'Julio': 7,
 'Agosto': 8,
 'Septiembre': 9,
 'Octubre': 10,
 'Noviembre': 11,
 'Diciembre': 12}

In [20]:
columnas =  datos.columns
columnas

Index(['Año', 'Mes', 'Marca', 'Modelo', 'Tipo', 'Segmento', 'Origen',
       'País origen', 'Cantidad'],
      dtype='object', name=4)

# Revisar el número de valores faltantes

In [27]:
## Faltantes por columnas 
for columna in columnas:
    print(sum(datos[columna].isna()))

6
6
6
6
6
6
6
6
6

### Revisar el tipo de datos

In [31]:
datos.dtypes

4
Año            object
Mes               str
Marca             str
Modelo            str
Tipo              str
Segmento          str
Origen            str
País origen       str
Cantidad       object
dtype: object

In [32]:
## Ver las fials con valores faltantes 

datos[datos['Año'].isna()]

4       Año  Mes Marca Modelo Tipo Segmento Origen País origen Cantidad
107381  NaN  NaN   NaN    NaN  NaN      NaN    NaN         NaN      NaN
107382  NaN  NaN   NaN    NaN  NaN      NaN    NaN         NaN      NaN
107383  NaN  NaN   NaN    NaN  NaN      NaN    NaN         NaN      NaN
107384  NaN  NaN   NaN    NaN  NaN      NaN    NaN         NaN      NaN
107385  NaN  NaN   NaN    NaN  NaN      NaN    NaN         NaN      NaN
107386  NaN  NaN   NaN    NaN  NaN      NaN    NaN         NaN      NaN

In [34]:
datos = datos.dropna()

In [35]:
## Faltantes por columnas 
for columna in columnas:
    print(sum(datos[columna].isna()))

0
0
0
0
0
0
0
0
0

In [37]:
datos['Mes'] = datos['Mes'].map(meses)

In [40]:
## Crear el campo de fecha 
datos["date"] = pd.to_datetime(datos["Año"].astype('str')+ "-" + datos["Mes"].astype('str')+'-01', format="%Y-%m-%d")

In [41]:
datos.dtypes

4
Año                    object
Mes                     int64
Marca                     str
Modelo                    str
Tipo                      str
Segmento                  str
Origen                    str
País origen               str
Cantidad               object
date           datetime64[us]
dtype: object